version: '3.8'

services:

  web-uat:
    container_name: web-cont-uat
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn goal_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.uat
    depends_on:
      - db-uat

  db-uat:
    container_name: db-uat-cont
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.uat.db

  nginx-proxy-uat:
    container_name: nginx-proxy-uat-cont
    build: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web-uat

  acme-companion-uat:
    container_name: acme-companion-uat-cont
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.uat.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy-uat

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
