version: '3.8'

services:

  web:
    container_name: web-cont
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn goal_tracker.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: db-cont
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
