version: '3.8'

services:

  web-stg:
    container_name: web-stg-cont
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: 054372962176.dkr.ecr.eu-central-1.amazonaws.com/gtrepo:web-stg
    command: gunicorn goal_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.staging

  nginx-proxy-stg:
    container_name: nginx-proxy-stg
    build: nginx
    image: 054372962176.dkr.ecr.eu-central-1.amazonaws.com/gtrepo:nginx-proxy-stg
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web-stg

  nginx-proxy-letsencrypt-stg:
    container_name: nginx-proxy-letsencrypt-stg
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy-stg

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
