# Generated by Django 4.0.3 on 2022-03-11 21:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('req_abstynence_time', models.DurationField(blank=True)),
                ('icon', models.ImageField(default='icon.jpg', upload_to='icons/milestones/')),
                ('is_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sentance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 3, 11, 21, 0, 25, 320998, tzinfo=utc))),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.milestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
