# Generated by Django 4.0.3 on 2022-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
