# Generated by Django 4.0.3 on 2022-03-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='milestone',
        ),
        migrations.AddField(
            model_name='milestone',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='req_abstynence_time',
            field=models.DurationField(null=True),
        ),
    ]
