# Generated by Django 4.0.3 on 2022-03-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_milestone_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='icon',
        ),
    ]
